version = 1
SPDX-PackageName = "yew-nav-link"
SPDX-PackageSupplier = "RAprogramm <andrey.rozanov.vl@gmail.com>"
SPDX-PackageDownloadLocation = "https://github.com/RAprogramm/yew-nav-link"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024-2025 RAprogramm <andrey.rozanov.vl@gmail.com>"
SPDX-License-Identifier = "MIT"
